# Generated by Django 4.2.9 on 2024-11-10 05:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0002_coupon'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('rut', models.CharField(blank=True, max_length=10)),
                ('sex', models.CharField(default='M', max_length=1, verbose_name='Sexo')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nombre de usuario')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de teléfono')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/', verbose_name='Foto de perfil')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Último inicio de sesión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateField(verbose_name='Fecha de registro')),
                ('number_order', models.CharField(max_length=255, verbose_name='Número de orden')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Total')),
                ('state', models.CharField(blank=True, choices=[('0', 'En proceso'), ('1', 'Enviado'), ('2', 'Entregado'), ('3', 'pagado'), ('4', 'Cancelado')], default=0, max_length=255, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.product')),
            ],
        ),
    ]
