# Generated by Django 4.2.9 on 2024-11-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_coupon'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sexo',
        ),
        migrations.AddField(
            model_name='client',
            name='sex',
            field=models.CharField(default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateField(verbose_name='Fecha de registro')),
                ('number_order', models.CharField(max_length=255, verbose_name='Número de orden')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Total')),
                ('state', models.CharField(blank=True, choices=[('0', 'En proceso'), ('1', 'Enviado'), ('2', 'Entregado'), ('3', 'pagado'), ('4', 'Cancelado')], default=0, max_length=255, verbose_name='Estado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='details_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='client.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.product')),
            ],
        ),
    ]
